In [33]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [34]:
data = pd.read_csv('titanic.csv')

In [35]:
data

,Passengerid,Age,Fare,Sex,sibsp,zero,zero.1,zero.2,zero.3,zero.4,...,zero.12,zero.13,zero.14,Pclass,zero.15,zero.16,Embarked,zero.17,zero.18,2urvived
0,1,22.0,7.2500,0,1,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
1,2,38.0,71.2833,1,1,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,1
2,3,26.0,7.9250,1,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,1
3,4,35.0,53.1000,1,1,0,0,0,0,0,...,0,0,0,1,0,0,2.0,0,0,1
4,5,35.0,8.0500,0,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
5,6,28.0,8.4583,0,0,0,0,0,0,0,...,0,0,0,3,0,0,1.0,0,0,0
6,7,54.0,51.8625,0,0,0,0,0,0,0,...,0,0,0,1,0,0,2.0,0,0,0
7,8,2.0,21.0750,0,3,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
8,9,27.0,11.1333,1,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,1
9,10,14.0,30.0708,1,1,0,0,0,0,0,...,0,0,0,2,0,0,0.0,0,0,1
10,11,4.0,16.7000,1,1,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,1
11,12,58.0,26.5500,1,0,0,0,0,0,0,...,0,0,0,1,0,0,2.0,0,0,1
12,13,20.0,8.0500,0,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
13,14,39.0,31.2750,0,1,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
14,15,14.0,7.8542,1,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
15,16,55.0,16.0000,1,0,0,0,0,0,0,...,0,0,0,2,0,0,2.0,0,0,1
16,17,2.0,29.1250,0,4,0,0,0,0,0,...,0,0,0,3,0,0,1.0,0,0,0
17,18,28.0,13.0000,0,0,0,0,0,0,0,...,0,0,0,2,0,0,2.0,0,0,1
18,19,31.0,18.0000,1,1,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
19,20,28.0,7.2250,1,0,0,0,0,0,0,...,0,0,0,3,0,0,0.0,0,0,1
20,21,35.0,26.0000,0,0,0,0,0,0,0,...,0,0,0,2,0,0,2.0,0,0,0
21,22,34.0,13.0000,0,0,0,0,0,0,0,...,0,0,0,2,0,0,2.0,0,0,1
22,23,15.0,8.0292,1,0,0,0,0,0,0,...,0,0,0,3,0,0,1.0,0,0,1
23,24,28.0,35.5000,0,0,0,0,0,0,0,...,0,0,0,1,0,0,2.0,0,0,1
24,25,8.0,21.0750,1,3,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
25,26,38.0,31.3875,1,1,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,1
26,27,28.0,7.2250,0,0,0,0,0,0,0,...,0,0,0,3,0,0,0.0,0,0,0
27,28,19.0,263.0000,0,3,0,0,0,0,0,...,0,0,0,1,0,0,2.0,0,0,0
28,29,28.0,7.8792,1,0,0,0,0,0,0,...,0,0,0,3,0,0,1.0,0,0,1
29,30,28.0,7.8958,0,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1279,1280,21.0,7.7500,0,0,0,0,0,0,0,...,0,0,0,3,0,0,1.0,0,0,0
1280,1281,6.0,21.0750,0,3,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
1281,1282,23.0,93.5000,0,0,0,0,0,0,0,...,0,0,0,1,0,0,2.0,0,0,0
1282,1283,51.0,39.4000,1,0,0,0,0,0,0,...,0,0,0,1,0,0,2.0,0,0,0
1283,1284,13.0,20.2500,0,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
1284,1285,47.0,10.5000,0,0,0,0,0,0,0,...,0,0,0,2,0,0,2.0,0,0,0
1285,1286,29.0,22.0250,0,3,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
1286,1287,18.0,60.0000,1,1,0,0,0,0,0,...,0,0,0,1,0,0,2.0,0,0,0
1287,1288,24.0,7.2500,0,0,0,0,0,0,0,...,0,0,0,3,0,0,1.0,0,0,0
1288,1289,48.0,79.2000,1,1,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,0
1289,1290,22.0,7.7750,0,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
1290,1291,31.0,7.7333,0,0,0,0,0,0,0,...,0,0,0,3,0,0,1.0,0,0,0
1291,1292,30.0,164.8667,1,0,0,0,0,0,0,...,0,0,0,1,0,0,2.0,0,0,0
1292,1293,38.0,21.0000,0,1,0,0,0,0,0,...,0,0,0,2,0,0,2.0,0,0,0
1293,1294,22.0,59.4000,1,0,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,0
1294,1295,17.0,47.1000,0,0,0,0,0,0,0,...,0,0,0,1,0,0,2.0,0,0,0
1295,1296,43.0,27.7208,0,1,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,0
1296,1297,20.0,13.8625,0,0,0,0,0,0,0,...,0,0,0,2,0,0,0.0,0,0,0
1297,1298,23.0,10.5000,0,1,0,0,0,0,0,...,0,0,0,2,0,0,2.0,0,0,0
1298,1299,50.0,211.5000,0,1,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,0
1299,1300,28.0,7.7208,1,0,0,0,0,0,0,...,0,0,0,3,0,0,1.0,0,0,0
1300,1301,3.0,13.7750,1,1,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
1301,1302,28.0,7.7500,1,0,0,0,0,0,0,...,0,0,0,3,0,0,1.0,0,0,0
1302,1303,37.0,90.0000,1,1,0,0,0,0,0,...,0,0,0,1,0,0,1.0,0,0,0
1303,1304,28.0,7.7750,1,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
1304,1305,28.0,8.0500,0,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
1305,1306,39.0,108.9000,1,0,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,0
1306,1307,38.5,7.2500,0,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
1307,1308,28.0,8.0500,0,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
1308,1309,28.0,22.3583,0,1,0,0,0,0,0,...,0,0,0,3,0,0,0.0,0,0,0

In [36]:
data.isnull().sum()

Passengerid    0
Age            0
Fare           0
Sex            0
sibsp          0
zero           0
zero.1         0
zero.2         0
zero.3         0
zero.4         0
zero.5         0
zero.6         0
Parch          0
zero.7         0
zero.8         0
zero.9         0
zero.10        0
zero.11        0
zero.12        0
zero.13        0
zero.14        0
Pclass         0
zero.15        0
zero.16        0
Embarked       2
zero.17        0
zero.18        0
2urvived       0
dtype: int64

In [48]:
M = data['Embarked'].mean()
M

1.4927314460596786

In [64]:
data.fillna(value=M,inplace=True)

In [65]:
data.isnull().sum()

Passengerid    0
Age            0
Fare           0
Sex            0
sibsp          0
zero           0
zero.1         0
zero.2         0
zero.3         0
zero.4         0
zero.5         0
zero.6         0
Parch          0
zero.7         0
zero.8         0
zero.9         0
zero.10        0
zero.11        0
zero.12        0
zero.13        0
zero.14        0
Pclass         0
zero.15        0
zero.16        0
Embarked       0
zero.17        0
zero.18        0
2urvived       0
dtype: int64

In [66]:
data.shape

(1309, 28)

In [67]:
data.head()

,Passengerid,Age,Fare,Sex,sibsp,zero,zero.1,zero.2,zero.3,zero.4,...,zero.12,zero.13,zero.14,Pclass,zero.15,zero.16,Embarked,zero.17,zero.18,2urvived
0,1,22.0,7.2500,0,1,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
1,2,38.0,71.2833,1,1,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,1
2,3,26.0,7.9250,1,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,1
3,4,35.0,53.1000,1,1,0,0,0,0,0,...,0,0,0,1,0,0,2.0,0,0,1
4,5,35.0,8.0500,0,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0

In [90]:
y = data.Sex
x = data.iloc[:,[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19]]

In [91]:
from sklearn.model_selection import train_test_split

In [92]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.30,random_state=1000)

In [93]:
x_train.head()

,Age,Fare,Sex,sibsp,zero,zero.1,zero.2,zero.3,zero.4,zero.5,zero.6,Parch,zero.7,zero.8,zero.9,zero.10,zero.11,zero.12,zero.13
25,38.0,31.3875,1,1,0,0,0,0,0,0,0,5,0,0,0,0,0,0,0
453,49.0,89.1042,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
746,16.0,20.2500,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
562,28.0,13.5000,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
980,2.0,23.0000,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0

In [94]:
y_train.head()

25     1
453    0
746    0
562    0
980    0
Name: Sex, dtype: int64

In [95]:
from sklearn.linear_model import LogisticRegression

In [96]:
model = LogisticRegression()

In [97]:
model.fit(x_train,y_train)

C:\Users\home\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [98]:
predict = model.predict(x_test)

In [99]:
y_test

658     0
286     0
706     1
982     0
53      1
1285    0
989     1
730     1
1053    1
533     1
1028    0
926     0
470     0
607     0
1113    1
1052    0
1192    0
638     1
434     0
1212    0
121     0
1000    0
1096    0
917     1
441     0
829     1
840     0
578     1
787     0
949     0
       ..
549     0
391     0
313     0
869     0
321     0
407     0
203     0
90      0
1223    0
1131    1
225     0
1030    0
367     1
288     0
1255    1
1267    1
565     0
1153    1
103     0
873     0
905     1
112     0
771     0
166     1
702     1
770     0
799     1
62      0
174     0
1256    1
Name: Sex, Length: 393, dtype: int64

In [100]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [101]:
accuracy_score(y_test,predict)

1.0

In [102]:
confusion_matrix(y_test,predict)

array([[273,   0],
       [  0, 120]], dtype=int64)

In [103]:
print(classification_report(y_test,predict))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       273
           1       1.00      1.00      1.00       120

   micro avg       1.00      1.00      1.00       393
   macro avg       1.00      1.00      1.00       393
weighted avg       1.00      1.00      1.00       393